name: Docs

on:
  pull_request:
    paths:
      - "docs/mkdocs.yml"
  # Publish docs weekly
  schedule:
    - cron:  '0 9 * * 1'
  workflow_dispatch:
    inputs:
      is-new-version:
        type: boolean
        description: Deploying new version?
        default: false
        required: true
      version-number:
        type: string 
        description: The new version number for the website
        default: dev
        required: false
      djl-tag: 
        type: string
        description: The commit number (e.g. 6b642e1) for the tag of the new version of djl.
        default: 'https://github.com/deepjavalibrary/djl.git'
        required: false
      djl-serving-branch:
        type: string
        description: The url for the new branch corresponding to new version of djl-serving.
        default: 'https://github.com/deepjavalibrary/djl-serving.git'
        required: false
      djl-demo-tag:
        description: The commit number (e.g. 6b642e1) for the tag of the new version of djl-demo. 
        default: 'https://github.com/deepjavalibrary/djl-demo.git'
        required: false
      testing:
        type: boolean
        description: Is this a test run that will be build into gamma account?
        default: false
        required: false
      testing-credentials:
        description: If testing, enter the gamma account zsh credentials
        default: None
        required: false

jobs:
  documentation:
    # Change line below 
    if: github.repository == 'Varun-Dutta/djl'  
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17
          
      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install CN fonts
        run: sudo apt-get update && sudo apt-get install fonts-arphic-uming
        
      - name: install Python Dependencies
        run: pip3 install nbconvert mkdocs==1.4.3 mkdocs-exclude mknotebooks mkdocs-material jupyter Pygments Markdown mike
        
      - name: Install IJava kernel
        run: |
          git clone https://github.com/frankfliu/IJava.git
          cd IJava/
          ./gradlew installKernel
          
      - name: Create website directory
        run:
          cd .. 
          mkdir site
          
      - name: Set-up Versioned Website Directory 
        if: ${{github.event.inputs.is-new-version}}
        uses: actions/checkout@v4
        with: 
          ref: ${{github.event.inputs.djl-tag}}
          
      - name: Set-up Dev Directory
        if: ${{!github.event.inputs.is-new-version}}
        uses: actions/checkout@v4
        
      - name: Add mybinder link
        run: |
          python3 tools/scripts/add_online_runner.py
          
      - name: Clone DJL-Serving and DJL Demos
        env:
          NEW_VERSION_BOOLEAN: ${{github.event.inputs.is-new-version}}
          DJL_DEMO_SHA: ${{github.event.inputs.djl-demo-tag}}
          DJL_SERVING_SHA: ${{github.event.inputs.djl-serving-branch}}
        run: |
          cd docs
          git clone https://github.com/deepjavalibrary/djl-demo.git demos
          git clone https://github.com/deepjavalibrary/djl-serving.git serving
          if [ "$NEW_VERSION_BOOLEAN" = "true" ]; then
            cd demos
            git checkout $DJL_DEMO_SHA
            cd ../serving
            git checkout $DJL_SERVING_SHA
            cd ..
          fi
        shell: bash
        
      - name: run Notebooks
        run: |
          cd docs/demos/jupyter
          bash test_notebook.sh

      - name: Configure AWS Test Credentials
        if: ${{github.event.inputs.testing}}
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::185921645874:role/UpdateWebsite
          aws-region: us-east-1
      
      - name: Configure AWS Credentials
        if: ${{github.event_name != 'pull_request' && github.event.inputs.testing != 'true'}}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Sync gh-pages
        env: 
          TESTING: ${{github.event.inputs.testing}}
        run: |
          mike delete --all
          git checkout gh-pages
          if [$TESTING = 'true']; then
            aws s3 sync s3://updated-documentation-website/website . 
          else
            aws s3 sync s3://djl-ai/documentation/nightly .
          fi
          git checkout master
        shell: bash

        #Double Check
      - name: build docs
        env:
          VERSION_NUMBER: ${{github.event.inputs.version-number}}
          IS_NEW_VERSION: ${{github.event.inputs.is-new-version}}
        run: |
          cd docs
          export DJL_DISABLE_PROGRESS_BAR=true
          if [ '$IS_NEW_VERSION' = 'true' ]; then
            export DJL_DISABLE_PROGRESS_BAR=true
            mike deploy $VERSION_NUMBER latest
          else
            mike deploy dev 
            mike set-default dev
        shell: bash
            
      - name: Copy files to S3 with the AWS CLI
        if: github.event_name != 'pull_request'
        env:
          TESTING: ${{github.event.inputs.testing}}
        run: |
          git checkout gh-pages
          if [$TESTING = 'true']; then
            aws s3 sync . s3://updated-documentation-website/website --delete
          else
            aws s3 sync . s3://djl-ai/documentation/nightly --delete
            aws cloudfront create-invalidation --distribution-id E733IIDCG0G5U --paths "/*"
          fi
        shell: bash
        
